create extension if not exists pgcrypto;

create table if not exists app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists users_mips (
  id uuid primary key default gen_random_uuid(),
  user_number bigint generated by default as identity unique,
  mips_id text unique,
  nombre text not null,
  servicio text not null,
  turno text not null,
  device_key text,
  fecha_registro timestamptz not null default now(),
  ultimo_mes text not null default to_char(now() at time zone 'America/Ciudad_Juarez', 'YYYY-MM'),
  activo boolean not null default true,
  notas text default ''
);

create table if not exists attendance_records (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  fecha text not null,
  hora text not null,
  user_id uuid references users_mips(id),
  mips_id text not null,
  nombre text not null,
  servicio text not null,
  turno text not null,
  tipo text not null check (tipo in ('entrada', 'salida')),
  estado_qr text not null,
  dispositivo text,
  folio_registro text unique not null
);

alter table app_settings enable row level security;
alter table users_mips enable row level security;
alter table attendance_records enable row level security;

insert into app_settings (key, value)
values
  ('qr_secret', encode(extensions.gen_random_bytes(32), 'hex')),
  ('admin_password_sha256', encode(extensions.digest('Starmedica.26', 'sha256'), 'hex'))
on conflict (key) do nothing;

create or replace function private_setting(setting_key text)
returns text
language sql
security definer
set search_path = public
as $$
  select value from app_settings where key = setting_key
$$;

create or replace function make_qr_token(token_minute bigint)
returns text
language sql
security definer
set search_path = public
as $$
  select token_minute::text || '.' || encode(extensions.digest(private_setting('qr_secret') || ':' || token_minute::text, 'sha256'), 'hex')
$$;

create or replace function get_qr_payload(base_url text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  token_minute bigint;
  token text;
  clean_url text;
begin
  token_minute := floor(extract(epoch from now()) / 60);
  token := make_qr_token(token_minute);
  clean_url := split_part(base_url, '?', 1);

  return jsonb_build_object(
    'token', token,
    'url', clean_url || '?t=' || token,
    'serverTime', now()
  );
end;
$$;

create or replace function is_valid_qr_token(token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_minute bigint := floor(extract(epoch from now()) / 60);
begin
  return token = make_qr_token(current_minute)
    or token = make_qr_token(current_minute - 1);
end;
$$;

create or replace function user_to_json(u users_mips)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', u.mips_id,
    'nombre', u.nombre,
    'servicio', u.servicio,
    'turno', u.turno,
    'fecha_registro', to_char(u.fecha_registro at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY HH24:MI:SS'),
    'ultimo_mes', u.ultimo_mes,
    'activo', case when u.activo then 'SI' else 'NO' end
  )
$$;

create or replace function get_bootstrap(profile_id text default null, device_key_input text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  u users_mips;
begin
  select *
  into u
  from users_mips
  where activo = true
    and (
      (profile_id is not null and mips_id = profile_id)
      or (device_key_input is not null and device_key = device_key_input)
    )
  order by fecha_registro desc
  limit 1;

  return jsonb_build_object(
    'user', case when u.id is null then null else user_to_json(u) end,
    'serverTime', now(),
    'servicios', jsonb_build_array('Hospitalizacion 2do', 'Hospitalizacion 3ero', 'UCIA', 'Quirofano', 'Urgencias'),
    'turnos', jsonb_build_array('Matutino', 'Vespertino')
  );
end;
$$;

create or replace function is_out_of_schedule(turno text, tipo text, moment timestamptz)
returns boolean
language plpgsql
stable
as $$
declare
  total int;
begin
  total := extract(hour from moment at time zone 'America/Ciudad_Juarez')::int * 60
    + extract(minute from moment at time zone 'America/Ciudad_Juarez')::int;

  if turno = 'Matutino' and tipo = 'entrada' then
    return not (total between 420 and 435);
  elsif turno = 'Matutino' and tipo = 'salida' then
    return not (total between 900 and 915);
  elsif turno = 'Vespertino' and tipo = 'entrada' then
    return not (total between 840 and 855);
  elsif turno = 'Vespertino' and tipo = 'salida' then
    return not (total >= 1439 or total <= 120);
  end if;

  return true;
end;
$$;

create or replace function register_attendance(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  token text := payload->>'token';
  req_tipo text := lower(trim(payload->>'tipo'));
  req_id text := nullif(trim(payload->>'id'), '');
  req_device_key text := nullif(trim(payload->>'deviceKey'), '');
  req_nombre text := nullif(trim(payload->>'nombre'), '');
  req_servicio text := nullif(trim(payload->>'servicio'), '');
  req_turno text := nullif(trim(payload->>'turno'), '');
  req_dispositivo text := nullif(trim(payload->>'dispositivo'), '');
  u users_mips;
  now_local timestamptz := now();
  out_of_schedule boolean;
  new_folio text;
begin
  if not is_valid_qr_token(token) then
    raise exception 'QR expirado. Escanea el codigo nuevamente.';
  end if;

  if req_tipo not in ('entrada', 'salida') then
    raise exception 'Selecciona Entrada o Salida.';
  end if;

  select *
  into u
  from users_mips
  where activo = true
    and (
      (req_id is not null and mips_id = req_id)
      or (req_device_key is not null and device_key = req_device_key)
    )
  order by fecha_registro desc
  limit 1;

  if u.id is null then
    if req_nombre is null or req_servicio is null or req_turno is null then
      raise exception 'Completa nombre, servicio y turno.';
    end if;

    insert into users_mips (nombre, servicio, turno, device_key)
    values (req_nombre, req_servicio, req_turno, req_device_key)
    returning * into u;

    update users_mips
    set mips_id = 'MIPS-' || lpad(u.user_number::text, 4, '0')
    where id = u.id
    returning * into u;
  elsif req_device_key is not null and u.device_key is null then
    update users_mips
    set device_key = req_device_key
    where id = u.id
    returning * into u;
  end if;

  out_of_schedule := is_out_of_schedule(u.turno, req_tipo, now_local);
  new_folio := 'REG-' || to_char(now_local at time zone 'America/Ciudad_Juarez', 'YYYYMMDD-HH24MISS') || '-' || u.mips_id;

  insert into attendance_records (
    fecha, hora, user_id, mips_id, nombre, servicio, turno, tipo, estado_qr, dispositivo, folio_registro
  )
  values (
    to_char(now_local at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY'),
    to_char(now_local at time zone 'America/Ciudad_Juarez', 'HH24:MI:SS'),
    u.id,
    u.mips_id,
    u.nombre,
    u.servicio,
    u.turno,
    req_tipo,
    case when out_of_schedule then 'fuera de horario' else 'normal' end,
    req_dispositivo,
    new_folio
  );

  return jsonb_build_object(
    'ok', true,
    'user', user_to_json(u),
    'record', jsonb_build_object(
      'timestamp', to_char(now_local at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY HH24:MI:SS'),
      'fecha', to_char(now_local at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY'),
      'hora', to_char(now_local at time zone 'America/Ciudad_Juarez', 'HH24:MI:SS'),
      'id', u.mips_id,
      'nombre', u.nombre,
      'servicio', u.servicio,
      'turno', u.turno,
      'tipo', req_tipo,
      'estado_qr', case when out_of_schedule then 'fuera de horario' else 'normal' end,
      'dispositivo', req_dispositivo,
      'folio_registro', new_folio
    )
  );
end;
$$;

create or replace function admin_snapshot(password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if encode(extensions.digest(coalesce(password, ''), 'sha256'), 'hex') <> private_setting('admin_password_sha256') then
    raise exception 'Contraseña incorrecta.';
  end if;

  return jsonb_build_object(
    'registros', coalesce((
      select jsonb_agg(jsonb_build_object(
        'timestamp', to_char(created_at at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY HH24:MI:SS'),
        'fecha', fecha,
        'hora', hora,
        'id', mips_id,
        'nombre', nombre,
        'servicio', servicio,
        'turno', turno,
        'tipo', tipo,
        'estado_qr', estado_qr,
        'dispositivo', dispositivo,
        'folio_registro', folio_registro
      ) order by created_at)
      from attendance_records
    ), '[]'::jsonb),
    'usuarios', coalesce((
      select jsonb_agg(user_to_json(u) order by u.user_number)
      from users_mips u
    ), '[]'::jsonb)
  );
end;
$$;

grant execute on function get_qr_payload(text) to anon, authenticated;
grant execute on function get_bootstrap(text, text) to anon, authenticated;
grant execute on function register_attendance(jsonb) to anon, authenticated;
grant execute on function admin_snapshot(text) to anon, authenticated;

create or replace function is_admin_password(password text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select encode(extensions.digest(coalesce(password, ''), 'sha256'), 'hex') = private_setting('admin_password_sha256')
$$;

create or replace function normalize_admin_choice(value text, allowed text[], field_name text)
returns text
language plpgsql
stable
as $$
declare
  clean text := nullif(trim(value), '');
begin
  if clean is null or not (clean = any(allowed)) then
    raise exception 'Valor invalido para %.', field_name;
  end if;
  return clean;
end;
$$;

create or replace function parse_local_record_time(fecha_text text, hora_text text)
returns timestamptz
language plpgsql
stable
as $$
declare
  f text := trim(fecha_text);
  h text := trim(hora_text);
  parts text[];
  time_parts text[];
begin
  if f !~ '^\d{2}/\d{2}/\d{4}$' then
    raise exception 'Fecha invalida. Usa DD/MM/YYYY.';
  end if;

  if h !~ '^\d{2}:\d{2}(:\d{2})?$' then
    raise exception 'Hora invalida. Usa HH:MM o HH:MM:SS.';
  end if;

  parts := regexp_split_to_array(f, '/');
  time_parts := regexp_split_to_array(h, ':');

  return make_timestamptz(
    parts[3]::int,
    parts[2]::int,
    parts[1]::int,
    time_parts[1]::int,
    time_parts[2]::int,
    coalesce(time_parts[3], '0')::double precision,
    'America/Ciudad_Juarez'
  );
end;
$$;

create or replace function admin_snapshot(password text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_password(password) then
    raise exception 'Contraseña incorrecta.';
  end if;

  return jsonb_build_object(
    'registros', coalesce((
      select jsonb_agg(jsonb_build_object(
        'uuid', id,
        'timestamp', to_char(created_at at time zone 'America/Ciudad_Juarez', 'DD/MM/YYYY HH24:MI:SS'),
        'fecha', fecha,
        'hora', hora,
        'id', mips_id,
        'nombre', nombre,
        'servicio', servicio,
        'turno', turno,
        'tipo', tipo,
        'estado_qr', estado_qr,
        'dispositivo', dispositivo,
        'folio_registro', folio_registro
      ) order by created_at)
      from attendance_records
    ), '[]'::jsonb),
    'usuarios', coalesce((
      select jsonb_agg(user_to_json(u) || jsonb_build_object('uuid', u.id) order by u.user_number)
      from users_mips u
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function admin_update_record(password text, record_uuid uuid, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  req_fecha text := trim(payload->>'fecha');
  req_hora text := trim(payload->>'hora');
  req_nombre text := nullif(trim(payload->>'nombre'), '');
  req_servicio text;
  req_turno text;
  req_tipo text;
  req_estado text;
  req_created_at timestamptz;
begin
  if not is_admin_password(password) then
    raise exception 'Contraseña incorrecta.';
  end if;

  if req_nombre is null then
    raise exception 'El nombre no puede quedar vacio.';
  end if;

  req_servicio := normalize_admin_choice(payload->>'servicio', array['Hospitalizacion 2do', 'Hospitalizacion 3ero', 'UCIA', 'Quirofano', 'Urgencias'], 'servicio');
  req_turno := normalize_admin_choice(payload->>'turno', array['Matutino', 'Vespertino'], 'turno');
  req_tipo := normalize_admin_choice(lower(payload->>'tipo'), array['entrada', 'salida'], 'tipo');
  req_estado := normalize_admin_choice(lower(payload->>'estado_qr'), array['normal', 'fuera de horario'], 'estado');
  req_created_at := parse_local_record_time(req_fecha, req_hora);

  update attendance_records
  set
    fecha = req_fecha,
    hora = case when req_hora ~ '^\d{2}:\d{2}$' then req_hora || ':00' else req_hora end,
    created_at = req_created_at,
    nombre = req_nombre,
    servicio = req_servicio,
    turno = req_turno,
    tipo = req_tipo,
    estado_qr = req_estado
  where id = record_uuid;

  if not found then
    raise exception 'Registro no encontrado.';
  end if;

  return admin_snapshot(password);
end;
$$;

create or replace function admin_delete_record(password text, record_uuid uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_password(password) then
    raise exception 'Contraseña incorrecta.';
  end if;

  delete from attendance_records where id = record_uuid;
  if not found then
    raise exception 'Registro no encontrado.';
  end if;

  return admin_snapshot(password);
end;
$$;

create or replace function admin_update_user(password text, user_uuid uuid, payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  req_nombre text := nullif(trim(payload->>'nombre'), '');
  req_servicio text;
  req_turno text;
  req_activo boolean := coalesce((payload->>'activo')::boolean, true);
begin
  if not is_admin_password(password) then
    raise exception 'Contraseña incorrecta.';
  end if;

  if req_nombre is null then
    raise exception 'El nombre no puede quedar vacio.';
  end if;

  req_servicio := normalize_admin_choice(payload->>'servicio', array['Hospitalizacion 2do', 'Hospitalizacion 3ero', 'UCIA', 'Quirofano', 'Urgencias'], 'servicio');
  req_turno := normalize_admin_choice(payload->>'turno', array['Matutino', 'Vespertino'], 'turno');

  update users_mips
  set nombre = req_nombre, servicio = req_servicio, turno = req_turno, activo = req_activo
  where id = user_uuid;

  if not found then
    raise exception 'Personal no encontrado.';
  end if;

  return admin_snapshot(password);
end;
$$;

create or replace function admin_delete_user(password text, user_uuid uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not is_admin_password(password) then
    raise exception 'Contraseña incorrecta.';
  end if;

  update attendance_records set user_id = null where user_id = user_uuid;
  delete from users_mips where id = user_uuid;
  if not found then
    raise exception 'Personal no encontrado.';
  end if;

  return admin_snapshot(password);
end;
$$;

grant execute on function admin_update_record(text, uuid, jsonb) to anon, authenticated;
grant execute on function admin_delete_record(text, uuid) to anon, authenticated;
grant execute on function admin_update_user(text, uuid, jsonb) to anon, authenticated;
grant execute on function admin_delete_user(text, uuid) to anon, authenticated;
